### ISSUE TITLE
Need to add CLI and GUI for the software

### ISSUE THREAD

**Issue by aharwood2** [aharwood2/JBlock2D#10]
Need to be able to run the software without using an IDE so that it is easier for users. Can do this with some kind of batch file or bash script to call the Java compiler and run the application etc.

**Comment by aharwood2** [comment]
Instead of a CLI, we decided to go for a GUI. Initial GUI testing looks promising allowing user to pick output location as well as input files. Need to consider a few things:    

1. Need a check box to say whether input file is batched or not -- or have the software recognise it for itself.    
2. Need to have the paths and files chosen visible to the user before they click run.    
3. Could do with a compact layout like this:
![img_20180713_152616_716](https://user-images.githubusercontent.com/8614261/42697075-02d0ce90-86b2-11e8-8886-7f32c7129ee3.jpg) which makes better use of frames to order the information.    
4. Will need to create executable releases and tag them on the master to avoid users having to build the code.    
5. Need to put the version number somewhere in the code and on the GUI for reference.

**Comment by jamesgill1997** [comment]
GUI added with the ability to choose which patterns to create from a chosen input file and output directory.
