### ISSUE TITLE
Add a dxf file as a visualiser when selecting options

### ISSUE THREAD

**Issue by jamesgill1997** [aharwood2/JBlock2D#37]
So that you can see what the output will be before clicking run

**Comment by jamesgill1997** [comment]
Nice idea but rejected in favour of an image on the analysis and pattern tabs showing all layers at once. Anything more than that is overkill.

**Comment by aharwood2** [comment]
Still not implemented as we wished so re-opening.

**Comment by aharwood2** [comment]
I have an idea of how we can do this with little effort.

**Comment by aharwood2** [comment]
Hacked the code to generate sample images with bitcode suffixes for this. It is not a fantastic solution but it is functional. Need to batch convert and scale DXF to JPEG then I'll add the event methods to the code to finish the implementation.

**Comment by aharwood2** [comment]
Can be done with only 6 images if using alpha channel. Partial fix in progress. Will complete tomorrow.

**Comment by aharwood2** [comment]
This is now done and merged into development.
