### ISSUE TITLE
Reader for batch output

### ISSUE THREAD

**Issue by aharwood2** [aharwood2/JBlock2D#4]
Current input file reader only reads single scan measurements from a single file. We have the facility to batch output measurements (see attached file). We should implement a new reader to extract multiple scans from this type of input.
[BatchScanData.txt](https://github.com/aharwood2/JBlock2D/files/1937834/BatchScanData.txt)

**Comment by aharwood2** [comment]
Need to preserve the old reader for legacy reasons and offer both.

**Comment by jamesgill1997** [comment]
Issue fixed by adding an alternative method for processing batch data files. Tested with a sample data file.
