### ISSUE TITLE
Add more file inputs to the software

### ISSUE THREAD

**Issue by jamesgill1997** [aharwood2/JBlock2D#41]
Add more test input files for people to use who don't have access to the custom measurements or software and organise them for easier use.

**Comment by aharwood2** [comment]
In general, we should just update things like the readme with a "tutorial" as to how to use the software to create patterns from some sample input files.

**Comment by jamesgill1997** [comment]
More input files have been added to the package, and the batch files are named according to how many data sets they possess. Folders have also been created for easy accessing.
