### ISSUE TITLE
File Chooser should be easier to use

### ISSUE THREAD

**Issue by aharwood2** [aharwood2/JBlock2D#46]
The File Chooser behaviour is a bit clunky. Couple of scenarios would be useful.    

1. If wanting to change the input file, a second click on `Open` button should automatically start navigation in the directory that was last used rather than resorting to default.    

2. Can we leverage the OS better and use a proper Windows Explorer window for file navigation rather than the horrible swing one? I would like to be able to paste a path in the bar at the top to navigate to folders faster.

**Comment by jamesgill1997** [comment]
Both parts of this have been implemented, file explorer is still not optimal but there are still options for changing if needed.
