### ISSUE TITLE
Illustrate keypoints

### ISSUE THREAD

**Issue by aharwood2** [aharwood2/JBlock2D#5]
We need to modify the DXF file writer to write out the keypoints as circles on a separate layer.

**Comment by aharwood2** [comment]
We should make it so we can turn this output option on and off.

**Comment by aharwood2** [comment]
We can also add an option to display the absolute coordinates of each point above it.

**Comment by jamesgill1997** [comment]
A new layer has been added to the dxf writer to illustrate the keypoints with circles
