### ISSUE TITLE
Add notches to DXF output

### ISSUE THREAD

**Issue by aharwood2** [aharwood2/JBlock2D#6]
The blocks will benefit from having notches added at certain points as triangles. Need to discuss with users as to how these can be added and where for each drafting method.

**Comment by aharwood2** [comment]
Notches are little triangles that represent major construction lines such as hip level and upper hip level etc. We could have these represented as construction lines.

**Comment by jamesgill1997** [comment]
Add the construction line points as pairs rather than two individually

**Comment by jamesgill1997** [comment]
Construction lines have been added as a new layer on the dxf writer
